INSERT INTO PUBLIC.PET_TYPE (NAME) VALUES ('Dog');
INSERT INTO PUBLIC.PET_TYPE (NAME) VALUES ('Cat');
INSERT INTO PUBLIC.PET_TYPE (NAME) VALUES ('Bird');

INSERT INTO PUBLIC.PET (PET_TYPE_ID, NAME, BIRTH_DATE) VALUES (1, 'Sassu', '2022-05-01');
INSERT INTO PUBLIC.PET (PET_TYPE_ID, NAME, BIRTH_DATE) VALUES (2, 'Miisu', '2021-04-01');
INSERT INTO PUBLIC.PET (PET_TYPE_ID, NAME, BIRTH_DATE) VALUES (3, 'Linnu', '2020-03-01');

INSERT INTO PUBLIC.CUSTOMER (FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ('Toomas', 'Ahoi', '13579');
INSERT INTO PUBLIC.CUSTOMER (FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ('Malle', 'Pall', '246801');
INSERT INTO PUBLIC.CUSTOMER (FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ('Linda', 'Kivi', '123456');

INSERT INTO PUBLIC.SALE (PET_ID, CUSTOMER_ID, SALE_DATE, SALE_PRICE) VALUES (1, 1, '2022-04-01', 250.00);
INSERT INTO PUBLIC.SALE (PET_ID, CUSTOMER_ID, SALE_DATE, SALE_PRICE) VALUES (2, 2, '2021-04-01', 150.00);
INSERT INTO PUBLIC.SALE (PET_ID, CUSTOMER_ID, SALE_DATE, SALE_PRICE) VALUES (3, 3, '2020-03-01', 200.00);
